import { existsSync, watch } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { gzipSync } from "node:zlib";
import { defineThemes } from "./index";
import { VarthConfig } from "./types";

export type CliIO = {
  cwd: string;
  log: (line: string) => void;
  color: boolean;
};

const VERSION: string = createRequire(import.meta.url)(
  "../package.json",
).version;

// --- paint ------------------------------------------------------------------

const paint = (on: boolean) => {
  const wrap = (open: string, close = "\x1b[0m") =>
    on ? (s: string) => `${open}${s}${close}` : (s: string) => s;
  return {
    blue: wrap("\x1b[34m"),
    green: wrap("\x1b[32m"),
    yellow: wrap("\x1b[33m"),
    red: wrap("\x1b[31m"),
    dim: wrap("\x1b[2m"),
    bold: wrap("\x1b[1m"),
    /** Two truecolor blocks painted with the given rgb. */
    swatch: (r: number, g: number, b: number) =>
      on ? `\x1b[38;2;${r};${g};${b}m██\x1b[0m` : "██",
  };
};

const hexToRgb = (value: string): [number, number, number] | null => {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(value.trim());
  if (!m) return null;
  let h = m[1] as string;
  if (h.length === 3) h = [...h].map((c) => c + c).join("");
  const n = parseInt(h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};

const kb = (bytes: number) => `${(bytes / 1024).toFixed(2)} kB`;

// --- config -----------------------------------------------------------------

const CONFIG_NAMES = [
  "varth.config.ts",
  "varth.config.mts",
  "varth.config.mjs",
  "varth.config.js",
];

const findConfig = (cwd: string): string | null => {
  for (const name of CONFIG_NAMES) {
    const p = join(cwd, name);
    if (existsSync(p)) return p;
  }
  return null;
};

const loadConfig = async (path: string): Promise<VarthConfig> => {
  let mod: { default?: VarthConfig };
  try {
    // cache-bust so --watch picks up edits
    mod = await import(`${pathToFileURL(path).href}?t=${Date.now()}`);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    if (msg.includes("Unknown file extension"))
      throw new Error(
        `could not load ${path} — TypeScript configs need Node ≥ 22.18 ` +
          `(native type stripping). Upgrade Node or use varth.config.mjs.`,
      );
    throw new Error(`could not load ${path}\n  ${msg}`);
  }
  const config = mod.default;
  if (!config || typeof config !== "object" || !("themes" in config))
    throw new Error(
      `${path} must default-export a config object with a "themes" field`,
    );
  return config;
};

// --- generated switcher --------------------------------------------------------

const switcherJS = (themeNames: string[], storageKey: string) => `// generated by var-th — do not edit
const KEY = ${JSON.stringify(storageKey)};
const NAMES = ${JSON.stringify(themeNames)};

const apply = (theme) => {
  if (typeof document === "undefined") return;
  const el = document.documentElement;
  if (theme === "system") el.removeAttribute("data-theme");
  else el.setAttribute("data-theme", theme);
};

export const setTheme = (theme) => {
  if (theme !== "system" && !NAMES.includes(theme))
    throw new TypeError(\`[varth] unknown theme "\${theme}"\`);
  apply(theme);
  try {
    localStorage.setItem(KEY, theme);
  } catch {}
};

export const getTheme = () => {
  if (typeof document !== "undefined") {
    const attr = document.documentElement.getAttribute("data-theme");
    if (attr && NAMES.includes(attr)) return attr;
  }
  try {
    const s = localStorage.getItem(KEY);
    if (s === "system" || NAMES.includes(s)) return s;
  } catch {}
  return "system";
};

// re-apply the saved choice on import
if (typeof document !== "undefined") {
  try {
    const s = localStorage.getItem(KEY);
    if (s === "system" || NAMES.includes(s)) apply(s);
  } catch {}
}
`;

const switcherDTS = (typeUnions: string) => `${typeUnions}
export declare function setTheme(theme: ThemeName | "system"): void;
export declare function getTheme(): ThemeName | "system";
`;

// --- gen ----------------------------------------------------------------------

const generate = async (io: CliIO, configPath: string) => {
  const p = paint(io.color);
  const started = performance.now();

  const config = await loadConfig(configPath);
  const th = defineThemes(config);

  const cssPath = resolve(io.cwd, config.out?.css ?? "varth.css");
  const css = th.toCSS();
  await writeFile(cssPath, css);

  const tokenCount = Object.keys(
    config.themes[th.themeNames[0] ?? ""] ?? {},
  ).length;
  const strategy = css.includes("light-dark(") ? "light-dark" : "attribute";
  io.log(
    `${p.green("✓")} ${tokenCount} tokens · ${th.themeNames.length} themes · strategy: ${p.bold(strategy)}`,
  );
  io.log(
    `${p.green("✎")} ${config.out?.css ?? "varth.css"}  ${kb(css.length)} · gzip ${kb(gzipSync(Buffer.from(css)).length)}`,
  );

  if (config.out?.js !== false) {
    const jsName = config.out?.js ?? "varth.js";
    const dtsName = jsName.replace(/\.(m?js)$/, "") + ".d.ts";
    const js = switcherJS(th.themeNames, config.storageKey ?? "varth-theme");
    const dts = switcherDTS(th.toTypes());
    await writeFile(resolve(io.cwd, jsName), js);
    await writeFile(resolve(io.cwd, dtsName), dts);
    io.log(`${p.green("✎")} ${jsName}  ${kb(js.length)} ${p.dim("· setTheme/getTheme, zero deps")}`);
    io.log(`${p.green("✎")} ${dtsName}  ${kb(dts.length)} ${p.dim("· types for the module above")}`);
  }

  io.log("");
  const pad = Math.max(...th.themeNames.map((n) => n.length));
  for (const name of th.themeNames) {
    const theme = config.themes[name] ?? {};
    const blocks = Object.entries(theme)
      .flatMap(([token, value]) => {
        const rgb = hexToRgb(value);
        return rgb
          ? [`${p.swatch(...rgb)}${p.dim(` ${token}`)}`]
          : [];
      })
      .slice(0, 6);
    if (blocks.length > 0)
      io.log(`  ${p.bold(name.padEnd(pad))}  ${blocks.join("  ")}`);
  }
  io.log("");
  io.log(`${p.blue("⚡")} done in ${Math.round(performance.now() - started)} ms`);
};

// --- init -----------------------------------------------------------------------

const CONFIG_TEMPLATE = `import type { VarthConfig } from "var-th";

// pencil on paper / chalk on board — replace with your brand
const config: VarthConfig = {
  themes: {
    light: {
      accent: "#3d6fb4",
      bg: "#fdfcf7",
      text: "#2b2b33",
      muted: "#6f6f7a",
      border: "#e2e0d8",
      radius: "8px",
    },
    dark: {
      accent: "#7fa9e0",
      bg: "#212932",
      text: "#e7ecf2",
      muted: "#9aa7b5",
      border: "#3a4552",
      radius: "8px",
    },
  },
  properties: "auto", // @property for every color token
  out: {
    css: "varth.css",
    js: "varth.js", // typed setTheme/getTheme, false to disable
  },
};

export default config;
`;

const detectFramework = async (cwd: string) => {
  try {
    const pkg = JSON.parse(await readFile(join(cwd, "package.json"), "utf8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps.next) return "next";
    if (deps.vite) return "vite";
    if (deps.react) return "react";
  } catch {
    // no package.json — plain html project
  }
  return "none";
};

const init = async (io: CliIO) => {
  const p = paint(io.color);
  const existing = findConfig(io.cwd);
  if (existing) {
    io.log(`${p.yellow("⚠")} ${existing} already exists — run ${p.bold("varth gen")} instead`);
    return 0;
  }

  const configPath = join(io.cwd, "varth.config.ts");
  await writeFile(configPath, CONFIG_TEMPLATE);
  io.log(`${p.green("✏")} varth.config.ts scaffolded`);
  await generate(io, configPath);

  const fw = await detectFramework(io.cwd);
  io.log("");
  io.log(p.bold("next steps"));
  io.log(
    fw === "none"
      ? `  1. ${p.blue('<link rel="stylesheet" href="varth.css">')}`
      : `  1. ${p.blue('import "./varth.css"')}  ${p.dim(fw === "next" ? "← app/layout.tsx" : "← entry module")}`,
  );
  io.log(`  2. ${p.blue("background: var(--th-accent)")}  ${p.dim("anywhere")}`);
  io.log(`  3. ${p.blue('import { setTheme } from "./varth.js"')}  ${p.dim("typed, persisted, optional")}`);
  io.log(`     ${p.dim("npx varth gen --watch  ← during development")}`);
  return 0;
};

// --- main ------------------------------------------------------------------------

const HELP = (color: boolean) => {
  const p = paint(color);
  return [
    "",
    `${p.blue("var")}${p.dim("(−")}${p.bold("th")}${p.dim(")")} — design tokens in, modern CSS out`,
    "",
    p.bold("usage"),
    `  ${p.blue("varth init")}          scaffold varth.config.ts + first build`,
    `  ${p.blue("varth gen")}           config → CSS (+ .d.ts)`,
    `  ${p.blue("varth gen --watch")}   rebuild on every config change`,
    "",
    p.bold("config"),
    `  varth.config.ts — default export, see ${p.dim("VarthConfig")} in var-th`,
    "",
  ].join("\n");
};

export const main = async (argv: string[], io: CliIO): Promise<number> => {
  const p = paint(io.color);
  const [command, ...flags] = argv;

  if (command === "--version" || command === "-v") {
    io.log(VERSION);
    return 0;
  }
  if (!command || command === "--help" || command === "-h" || command === "help") {
    io.log(HELP(io.color));
    return command ? 0 : 1;
  }

  io.log("");
  io.log(`${p.blue("var")}${p.dim("(−")}${p.bold("th")}${p.dim(")")} ${p.dim(`v${VERSION}`)}`);
  io.log("");

  try {
    if (command === "init") return await init(io);

    if (command === "gen") {
      const configPath = findConfig(io.cwd);
      if (!configPath)
        throw new Error(
          `no varth.config.{ts,mts,mjs,js} in ${io.cwd} — run "varth init" first`,
        );
      io.log(`${p.dim("▸")} ${configPath.slice(io.cwd.length + 1)}`);
      await generate(io, configPath);

      if (flags.includes("--watch")) {
        io.log("");
        io.log(`${p.yellow("👀")} watching ${configPath.slice(io.cwd.length + 1)} — ^C to stop`);
        let timer: ReturnType<typeof setTimeout> | undefined;
        watch(configPath, () => {
          clearTimeout(timer);
          timer = setTimeout(async () => {
            io.log("");
            io.log(`${p.blue("↻")} config changed`);
            try {
              await generate(io, configPath);
            } catch (e) {
              io.log(`${p.red("✗")} ${e instanceof Error ? e.message : e}`);
            }
          }, 50);
        });
        await new Promise(() => {}); // run until ^C
      }
      return 0;
    }

    io.log(`${p.red("✗")} unknown command "${command}"`);
    io.log(HELP(io.color));
    return 1;
  } catch (e) {
    io.log(`${p.red("✗")} ${e instanceof Error ? e.message : e}`);
    return 1;
  }
};
